#!/bin/bash

# Check check for errors
if [ -z "$PYFILE" ]; then
  echo "PYFILE environment variable not set"
  exit 1
fi

if [ ! -f "$PYFILE" ]; then
  echo "Python file $PYFILE not found"
  exit 1
fi

python "$PYFILE"
